export const data = [
  {
    id: 1,
    title: 'Praiano',
    image:
      'https://res.cloudinary.com/amanda-caf/image/upload/v1652632996/portfolio/banner-praiano_bojowr.png',
    modal_images: [
      {
        id: 1,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907411/portfolio/Modal/Praiano/Praiano-1_suckkk.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908700/portfolio/Modal/Praiano/Praiano-1_2x_th6q19.jpg',
        tooltip: 'Amanda Café',
        altText: 'Primeira Foto do Portfólio Praiano',
      },
      {
        id: 2,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907411/portfolio/Modal/Praiano/Praiano-2_e2w14p.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908700/portfolio/Modal/Praiano/Praiano-2_2x_ndrvks.jpg',
        tooltip: 'Amanda Café',
        altText: 'Segunda Foto do Portfólio Praiano',
      },
      {
        id: 3,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907411/portfolio/Modal/Praiano/Praiano-3_trms61.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908700/portfolio/Modal/Praiano/Praiano-3_2x_alaocr.jpg',
        tooltip: 'Amanda Café',
        altText: 'Terceira Foto do Portfólio Praiano',
      },
      {
        id: 4,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907411/portfolio/Modal/Praiano/Praiano-4_bh8lf6.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908701/portfolio/Modal/Praiano/Praiano-4_2x_vaoyqw.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quarta Foto do Portfólio Praiano',
      },
      {
        id: 5,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907411/portfolio/Modal/Praiano/Praiano-5_et29ht.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908700/portfolio/Modal/Praiano/Praiano-5_2x_sopvvz.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quinta Foto do Portfólio Praiano',
      },
      {
        id: 6,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907411/portfolio/Modal/Praiano/Praiano-6_er79ra.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908701/portfolio/Modal/Praiano/Praiano-6_2x_omzgr9.jpg',
        tooltip: 'Amanda Café',
        altText: 'Sexta Foto do Portfólio Praiano',
      },
    ],
  },
  {
    id: 2,
    title: 'Casual',
    image:
      'https://res.cloudinary.com/amanda-caf/image/upload/v1652632996/portfolio/banner-casual_q3m6le.png',
    modal_images: [
      {
        id: 1,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907636/portfolio/Modal/Casual/Casual-1_mycqgp.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908912/portfolio/Modal/Casual/Casual-1_2x_gm5kbr.jpg',
        tooltip: 'Amanda Café',
        altText: 'Primeira Foto do Portfólio Casual',
      },
      {
        id: 2,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907636/portfolio/Modal/Casual/Casual-2_rvlhlb.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908912/portfolio/Modal/Casual/Casual-2_2x_kcryoc.jpg',
        tooltip: 'Amanda Café',
        altText: 'Segunda Foto do Portfólio Casual',
      },
      {
        id: 3,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907636/portfolio/Modal/Casual/Casual-3_swvuwx.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908911/portfolio/Modal/Casual/Casual-3_2x_zspjmx.jpg',
        tooltip: 'Amanda Café',
        altText: 'Terceira Foto do Portfólio Casual',
      },
      {
        id: 4,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907636/portfolio/Modal/Casual/Casual-4_llwi3g.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908911/portfolio/Modal/Casual/Casual-4_2x_m4im8q.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quarta Foto do Portfólio Casual',
      },
      {
        id: 5,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907636/portfolio/Modal/Casual/Casual-5_l96rtv.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908911/portfolio/Modal/Casual/Casual-5_2x_cim4a5.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quinta Foto do Portfólio Casual',
      },
      {
        id: 6,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907636/portfolio/Modal/Casual/Casual-6_faxvnj.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908911/portfolio/Modal/Casual/Casual-6_2x_ki5ig7.jpg',
        tooltip: 'Amanda Café',
        altText: 'Sexta Foto do Portfólio Casual',
      },
    ],
  },
  {
    id: 3,
    title: 'Urbano',
    image:
      'https://res.cloudinary.com/amanda-caf/image/upload/v1652632996/portfolio/banner-urbano_n8coy5.png',
    modal_images: [
      {
        id: 1,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907738/portfolio/Modal/Urbano/Urbano-1_hink08.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909044/portfolio/Modal/Urbano/Urbano-1_2x_h0ydtm.jpg',
        tooltip: 'Amanda Café',
        altText: 'Primeira Foto do Portfólio Urbano',
      },
      {
        id: 2,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907738/portfolio/Modal/Urbano/Urbano-2_ipzonj.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909044/portfolio/Modal/Urbano/Urbano-2_2x_a4rpo6.jpg',
        tooltip: 'Amanda Café',
        altText: 'Segunda Foto do Portfólio Urbano',
      },
      {
        id: 3,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907738/portfolio/Modal/Urbano/Urbano-3_ru81mm.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909044/portfolio/Modal/Urbano/Urbano-3_2x_hntjro.jpg',
        tooltip: 'Amanda Café',
        altText: 'Terceira Foto do Portfólio Urbano',
      },
      {
        id: 4,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907738/portfolio/Modal/Urbano/Urbano-4_zsqco8.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909044/portfolio/Modal/Urbano/Urbano-4_2x_tsovsn.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quarta Foto do Portfólio Urbano',
      },
      {
        id: 5,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907738/portfolio/Modal/Urbano/Urbano-5_qhpxzy.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909044/portfolio/Modal/Urbano/Urbano-5_2x_c5qpk9.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quinta Foto do Portfólio Urbano',
      },
    ],
  },
  {
    id: 4,
    title: 'Sensual',
    image:
      'https://res.cloudinary.com/amanda-caf/image/upload/v1652632996/portfolio/banner-sensual_xyvwok.png',
    modal_images: [
      {
        id: 1,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907881/portfolio/Modal/Sensual/Sensual-1_wlnkha.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909146/portfolio/Modal/Sensual/Sensual-1_2x_ud0ldu.jpg',
        tooltip: 'Amanda Café',
        altText: 'Primeira Foto do Portfólio Sensual',
      },
      {
        id: 2,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907881/portfolio/Modal/Sensual/Sensual-2_ik5cke.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909146/portfolio/Modal/Sensual/Sensual-2_2x_xk5ouh.jpg',
        tooltip: 'Amanda Café',
        altText: 'Segunda Foto do Portfólio Sensual',
      },
      {
        id: 3,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907881/portfolio/Modal/Sensual/Sensual-3_hnmk1w.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909146/portfolio/Modal/Sensual/Sensual-3_2x_scuxye.jpg',
        tooltip: 'Amanda Café',
        altText: 'Terceira Foto do Portfólio Sensual',
      },
      {
        id: 4,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907881/portfolio/Modal/Sensual/Sensual-4_kqszxx.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909147/portfolio/Modal/Sensual/Sensual-4_2x_ghjwba.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quarta Foto do Portfólio Sensual',
      },
      {
        id: 5,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907881/portfolio/Modal/Sensual/Sensual-5_y5locj.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909147/portfolio/Modal/Sensual/Sensual-5_2x_peeazc.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quinta Foto do Portfólio Sensual',
      },
      {
        id: 6,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907881/portfolio/Modal/Sensual/Sensual-6_vgpcwn.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909146/portfolio/Modal/Sensual/Sensual-6_2x_zj8qem.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quinta Foto do Portfólio Sensual',
      },
    ],
  },
  {
    id: 5,
    title: 'Criativo',
    image:
      'https://res.cloudinary.com/amanda-caf/image/upload/v1652632996/portfolio/banner-criativo_v17e5u.png',
    modal_images: [
      {
        id: 1,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907972/portfolio/Modal/Criativo/Criativo-1_hklfa8.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909302/portfolio/Modal/Criativo/Criativo-1_2x_wneyu5.jpg',
        tooltip: 'Amanda Café',
        altText: 'Primeira Foto do Portfólio Criativo',
      },
      {
        id: 2,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907973/portfolio/Modal/Criativo/Criativo-2_swp9sk.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909302/portfolio/Modal/Criativo/Criativo-2_2x_ujpmkt.jpg',
        tooltip: 'Amanda Café',
        altText: 'Segunda Foto do Portfólio Criativo',
      },
      {
        id: 3,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907972/portfolio/Modal/Criativo/Criativo-3_st3lwi.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909303/portfolio/Modal/Criativo/Criativo-3_2x_nblwmn.jpg',
        tooltip: 'Amanda Café',
        altText: 'Terceira Foto do Portfólio Criativo',
      },
      {
        id: 4,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907973/portfolio/Modal/Criativo/Criativo-4_ggtuhf.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909302/portfolio/Modal/Criativo/Criativo-4_2x_crrifp.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quarta Foto do Portfólio Criativo',
      },
      {
        id: 5,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907972/portfolio/Modal/Criativo/Criativo-5_lquzvi.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909302/portfolio/Modal/Criativo/Criativo-5_2x_dbx6rl.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quinta Foto do Portfólio Criativo',
      },
      {
        id: 6,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907972/portfolio/Modal/Criativo/Criativo-6_g8bnwd.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909302/portfolio/Modal/Criativo/Criativo-6_2x_ix2gcl.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quinta Foto do Portfólio Criativo',
      },
      {
        id: 7,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652907973/portfolio/Modal/Criativo/Criativo-7_j8n91a.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909303/portfolio/Modal/Criativo/Criativo-7_2x_fgvnoc.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quinta Foto do Portfólio Criativo',
      },
    ],
  },
  {
    id: 6,
    title: 'Estúdio',
    image:
      'https://res.cloudinary.com/amanda-caf/image/upload/v1652632996/portfolio/banner-estudio_wjwqud.png',
    modal_images: [
      {
        id: 1,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908114/portfolio/Modal/Estudio/Est%C3%BAdio-1_tbowxy.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909439/portfolio/Modal/Estudio/Est%C3%BAdio-1_2x_fzc44w.jpg',
        tooltip: 'Amanda Café',
        altText: 'Primeira Foto do Portfólio Estúdio',
      },
      {
        id: 2,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908114/portfolio/Modal/Estudio/Est%C3%BAdio-2_gy2kpn.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909439/portfolio/Modal/Estudio/Est%C3%BAdio-2_2x_gpjrtr.jpg',
        tooltip: 'Amanda Café',
        altText: 'Segunda Foto do Portfólio Estúdio',
      },
      {
        id: 3,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908114/portfolio/Modal/Estudio/Est%C3%BAdio-3_oj5n5d.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909439/portfolio/Modal/Estudio/Est%C3%BAdio-3_2x_rcuexi.jpg',
        tooltip: 'Amanda Café',
        altText: 'Terceira Foto do Portfólio Estúdio',
      },
      {
        id: 4,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908114/portfolio/Modal/Estudio/Est%C3%BAdio-4_ejarrt.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909440/portfolio/Modal/Estudio/Est%C3%BAdio-4_2x_ifm1tw.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quarta Foto do Portfólio Estúdio',
      },
      {
        id: 5,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908113/portfolio/Modal/Estudio/Est%C3%BAdio-5_vsd2ph.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909439/portfolio/Modal/Estudio/Est%C3%BAdio-5_2x_jdmldr.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quinta Foto do Portfólio Estúdio',
      },
      {
        id: 6,
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909303/portfolio/Modal/Criativo/Criativo-7_2x_fgvnoc.jpg',
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909439/portfolio/Modal/Estudio/Est%C3%BAdio-6_2x_vxhavn.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quinta Foto do Portfólio Estúdio',
      },
      {
        id: 7,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908115/portfolio/Modal/Estudio/Est%C3%BAdio-7_t08ykv.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909440/portfolio/Modal/Estudio/Est%C3%BAdio-7_2x_wz9qfi.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quinta Foto do Portfólio Estúdio',
      },
    ],
  },
  {
    id: 7,
    title: 'Casal',
    image:
      'https://res.cloudinary.com/amanda-caf/image/upload/v1652632996/portfolio/banner-casal_motkfc.png',
    modal_images: [
      {
        id: 1,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908216/portfolio/Modal/Casal/Casal-1_fcbvhn.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909529/portfolio/Modal/Casal/Casal-1_2x_ncntgr.jpg',
        tooltip: 'Amanda Café',
        altText: 'Primeira Foto do Portfólio Casal',
      },
      {
        id: 2,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908217/portfolio/Modal/Casal/Casal-2_xwixlw.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909530/portfolio/Modal/Casal/Casal-2_2x_awul1w.jpg',
        tooltip: 'Amanda Café',
        altText: 'Segunda Foto do Portfólio Casal',
      },
      {
        id: 3,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908217/portfolio/Modal/Casal/Casal-3_cbmioq.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909530/portfolio/Modal/Casal/Casal-3_2x_tvaatw.jpg',
        tooltip: 'Amanda Café',
        altText: 'Terceira Foto do Portfólio Casal',
      },
      {
        id: 4,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908217/portfolio/Modal/Casal/Casal-4_glkk1m.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909530/portfolio/Modal/Casal/Casal-4_2x_sdmhjm.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quarta Foto do Portfólio Casal',
      },
      {
        id: 5,
        src: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652908217/portfolio/Modal/Casal/Casal-5_hrcsnw.jpg',
        src2: 'https://res.cloudinary.com/amanda-caf/image/upload/v1652909529/portfolio/Modal/Casal/Casal-5_2x_gdqu1y.jpg',
        tooltip: 'Amanda Café',
        altText: 'Quinta Foto do Portfólio Casal',
      },
    ],
  },
];

export const breakPoints = [
  { width: 1, itemsToShow: 1 },
  { width: 380, itemsToShow: 2, itemsToScroll: 1 },
  { width: 550, itemsToShow: 4, itemsToScroll: 1 },
];

export const breakPoints2 = [
  { width: 1, itemsToShow: 1 },
  { width: 1200, itemsToShow: 2, itemsToScroll: 1 },
  { width: 700, itemsToShow: 3, itemsToScroll: 1 },
];
